name: Frontend CI

on:
  push:
    branches:
      - master
    paths:
      - 'app/client/web/**'
      - ".github/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
    steps:
      - uses: actions/checkout@v2
      - name: Build React app
        run : |
          ls -la
          cd app/client/web/budgetme
          npm i
          npm run build
      # docker build . -t ${{ secrets.WEB_FRONT_IMAGE }}
      - name: Publish frontend to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.WEB_FRONT_IMAGE }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./app/client/web/budgetme
