name: CI

on:  
  push:
   branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
    steps:
    - uses: actions/checkout@v1
    - name: Build app
      run: |
        cd server
        npm i
        npm run Build
        npm run test
    # - name: Build docker container
    #   uses: elgohr/Publish-Docker-Github-Action@master        
    #   with:
    #     name: kletskovg/budget:latest
    #     username: ${{secrets.DOCKER_LOGIN}}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     context: ./server
    # - name: Pull budget
    #   run: |
    #       curl ${{ secrets.PULL_BUDGET }}
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
    needs: build
    steps:
      - name: Build docker container
        uses: elgohr/Publish-Docker-Github-Action@master        
        with:
          name: kletskovg/budget:latest
          username: ${{secrets.DOCKER_LOGIN}}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./server
      - name: Pull budget
        run: |
            curl ${{ secrets.PULL_BUDGET }}